<?php

namespace Database\Seeders;

use App\Models\Imovel;
use App\Models\StatusImovel;
use App\Models\TipoImovel;
use Illuminate\Database\Seeder;

class ImovelSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $imoveis = [
            [
                'titulo' => 'Casa Moderna em Condomínio Fechado',
                'descricao' => 'Linda casa moderna com acabamento de alto padrão, localizada em condomínio fechado com segurança 24h. Possui 3 quartos, 2 banheiros, sala de estar, sala de jantar, cozinha planejada e área de lazer completa.',
                'tipo' => 'casa',
                'situacao' => 'vende-se',
                'status' => 'disponivel',
                'preco' => 850000.00,
                'area' => 180,
                'area_util' => 150,
                'terreno' => 300,
                'area_constr' => 150,
                'quartos' => 3,
                'banheiros' => 2,
                'vagas_garagem' => 2,
                'endereco' => 'Rua das Palmeiras, 123',
                'bairro' => 'Jardim Europa',
                'cidade' => 'Rio de Janeiro',
                'estado' => 'RJ',
                'pais' => 'Brasil',
                'cep' => '25900000',
                'caracteristicas' => [
                    'Piscina' => 'Sim',
                    'Churrasqueira' => 'Sim',
                    'Playground' => 'Sim',
                    'Academia' => 'Sim',
                ],
                'fotos' => [
                    'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?q=80&w=800&auto=format&fit=crop',
                    'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=800&auto=format&fit=crop',
                ],
                'videos' => [
                    'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
                ],
                'destaque' => true,
                'preco_iptu' => 1200.00,
                'preco_condominio' => 600.00,
            ],
            [
                'titulo' => 'Apartamento 2 Quartos - Centro',
                'descricao' => 'Apartamento bem localizado no centro da cidade, próximo a comércio, escolas e transporte público. Ideal para investimento ou moradia.',
                'tipo' => 'apartamento',
                'situacao' => 'vende-se',
                'status' => 'disponivel',
                'preco' => 320000.00,
                'area' => 65,
                'area_util' => 60,
                'terreno' => null,
                'area_constr' => 60,
                'quartos' => 2,
                'banheiros' => 1,
                'vagas_garagem' => 1,
                'endereco' => 'Rua Coronel Veiga, 456',
                'bairro' => 'Centro',
                'cidade' => 'Rio de Janeiro',
                'estado' => 'RJ',
                'pais' => 'Brasil',
                'cep' => '25900000',
                'caracteristicas' => [
                    'Portaria 24h' => 'Sim',
                    'Elevador' => 'Sim',
                    'Varanda' => 'Sim',
                ],
                'fotos' => [
                    'https://images.unsplash.com/photo-1570129477492-45c003edd2be?q=80&w=800&auto=format&fit=crop',
                ],
                'videos' => [
                    'https://www.youtube.com/watch?v=jNQXAC9IVRw',
                ],
                'destaque' => false,
                'preco_iptu' => 800.00,
                'preco_condominio' => 400.00,
            ],
            [
                'titulo' => 'Terreno Residencial - Piabetá',
                'descricao' => 'Terreno residencial com 500m², localizado em bairro tranquilo e em desenvolvimento. Ideal para construção de casa própria.',
                'tipo' => 'terreno',
                'situacao' => 'vende-se',
                'status' => 'disponivel',
                'preco' => 180000.00,
                'area' => 500,
                'area_util' => null,
                'terreno' => 500,
                'area_constr' => null,
                'quartos' => null,
                'banheiros' => null,
                'vagas_garagem' => null,
                'endereco' => 'Rua das Flores, 789',
                'bairro' => 'Piabetá',
                'cidade' => 'Rio de Janeiro',
                'estado' => 'RJ',
                'pais' => 'Brasil',
                'cep' => '25900000',
                'caracteristicas' => [
                    'Área Plana' => 'Sim',
                    'Esgoto' => 'Sim',
                    'Água' => 'Sim',
                    'Luz' => 'Sim',
                ],
                'fotos' => [
                    'https://images.unsplash.com/photo-1500382017468-9049fed747ef?q=80&w=800&auto=format&fit=crop',
                ],
                'destaque' => false,
                'preco_iptu' => 500.00,
                'preco_condominio' => 0.00,
            ],
            [
                'titulo' => 'Sala Comercial - Centro Empresarial',
                'descricao' => 'Sala comercial localizada em centro empresarial de alto padrão, com grande fluxo de pessoas. Ideal para lojas, consultórios ou escritórios.',
                'tipo' => 'comercial',
                'situacao' => 'vende-se',
                'status' => 'disponivel',
                'preco' => 450000.00,
                'area' => 80,
                'area_util' => 75,
                'terreno' => null,
                'area_constr' => 75,
                'quartos' => null,
                'banheiros' => 1,
                'vagas_garagem' => 2,
                'endereco' => 'Av. Automóvel Clube, 321',
                'bairro' => 'Centro',
                'cidade' => 'Rio de Janeiro',
                'estado' => 'RJ',
                'pais' => 'Brasil',
                'cep' => '25900000',
                'caracteristicas' => [
                    'Ar Condicionado' => 'Sim',
                    'Segurança 24h' => 'Sim',
                    'Estacionamento' => 'Sim',
                    'Elevador' => 'Sim',
                ],
                'fotos' => [
                    'https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=800&auto=format&fit=crop',
                ],
                'destaque' => true,
                'preco_iptu' => 1500.00,
                'preco_condominio' => 300.00,
            ],
            [
                'titulo' => 'Casa Térrea - Vila Nova',
                'descricao' => 'Casa térrea com 2 quartos, localizada em bairro residencial tranquilo. Ideal para família pequena ou investimento.',
                'tipo' => 'casa',
                'situacao' => 'vende-se',
                'status' => 'disponivel',
                'preco' => 280000.00,
                'area' => 120,
                'area_util' => 100,
                'terreno' => 200,
                'area_constr' => 100,
                'quartos' => 2,
                'banheiros' => 1,
                'vagas_garagem' => 1,
                'endereco' => 'Rua da Paz, 100',
                'bairro' => 'Vila Nova',
                'cidade' => 'Rio de Janeiro',
                'estado' => 'RJ',
                'pais' => 'Brasil',
                'cep' => '25900000',
                'caracteristicas' => [
                    'Quintal' => 'Sim',
                    'Área de Serviço' => 'Sim',
                ],
                'fotos' => [
                    'https://images.unsplash.com/photo-1568605114967-8130f3a36994?q=80&w=800&auto=format&fit=crop',
                ],
                'destaque' => false,
                'preco_iptu' => 600.00,
                'preco_condominio' => 200.00,
            ],
            [
                'titulo' => 'Apartamento 3 Quartos - Jardim Europa',
                'descricao' => 'Apartamento espaçoso com 3 quartos, sendo 1 suíte. Localizado em condomínio com área de lazer completa.',
                'tipo' => 'apartamento',
                'situacao' => 'aluga-se',
                'status' => 'disponivel',
                'preco' => 420000.00,
                'area' => 95,
                'area_util' => 85,
                'terreno' => null,
                'area_constr' => 85,
                'quartos' => 3,
                'banheiros' => 2,
                'vagas_garagem' => 2,
                'endereco' => 'Rua das Acácias, 200',
                'bairro' => 'Jardim Europa',
                'cidade' => 'Rio de Janeiro',
                'estado' => 'RJ',
                'pais' => 'Brasil',
                'cep' => '25900000',
                'caracteristicas' => [
                    'Suíte' => 'Sim',
                    'Varanda' => 'Sim',
                    'Área de Lazer' => 'Sim',
                ],
                'fotos' => [
                    'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?q=80&w=800&auto=format&fit=crop',
                ],
                'destaque' => false,
                'preco_iptu' => 900.00,
                'preco_condominio' => 500.00,
            ],
            [
                'titulo' => 'Casa de Alto Padrão - Santo Aleixo',
                'descricao' => 'Casa de alto padrão com 4 quartos, sendo 2 suítes. Localizada em condomínio fechado com segurança 24h.',
                'tipo' => 'casa',
                'situacao' => 'aluga-se',
                'status' => 'disponivel',
                'preco' => 1200000.00,
                'area' => 280,
                'area_util' => 250,
                'terreno' => 400,
                'area_constr' => 250,
                'quartos' => 4,
                'banheiros' => 3,
                'vagas_garagem' => 3,
                'endereco' => 'Rua das Orquídeas, 50',
                'bairro' => 'Santo Aleixo',
                'cidade' => 'Rio de Janeiro',
                'estado' => 'RJ',
                'pais' => 'Brasil',
                'cep' => '25900000',
                'caracteristicas' => [
                    '2 Suítes' => 'Sim',
                    'Piscina' => 'Sim',
                    'Churrasqueira' => 'Sim',
                    'Academia' => 'Sim',
                    'Playground' => 'Sim',
                ],
                'fotos' => [
                    'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?q=80&w=800&auto=format&fit=crop',
                ],
                'destaque' => true,
                'preco_iptu' => 2000.00,
                'preco_condominio' => 800.00,
            ],
            [
                'titulo' => 'Loja Comercial - Centro',
                'descricao' => 'Loja comercial bem localizada no centro da cidade, com grande fluxo de pessoas. Ideal para diversos tipos de comércio.',
                'tipo' => 'comercial',
                'situacao' => 'aluga-se',
                'status' => 'disponivel',
                'preco' => 380000.00,
                'area' => 60,
                'area_util' => 55,
                'terreno' => null,
                'area_constr' => 55,
                'quartos' => null,
                'banheiros' => 1,
                'vagas_garagem' => 1,
                'endereco' => 'Rua Coronel Veiga, 150',
                'bairro' => 'Centro',
                'cidade' => 'Rio de Janeiro',
                'estado' => 'RJ',
                'pais' => 'Brasil',
                'cep' => '25900000',
                'caracteristicas' => [
                    'Vitrine' => 'Sim',
                    'Ar Condicionado' => 'Sim',
                    'Banheiro' => 'Sim',
                ],
                'fotos' => [
                    'https://images.unsplash.com/photo-1441986300917-64674bd600d8?q=80&w=800&auto=format&fit=crop',
                ],
                'destaque' => false,
                'preco_iptu' => 700.00,
                'preco_condominio' => 300.00,
            ],
        ];

        foreach ($imoveis as $imovel) {
            $tipo = TipoImovel::where('nome', ucfirst($imovel['tipo']))->first();
            $status = StatusImovel::whereRaw('LOWER(nome) = ?', [strtolower($imovel['status'])])->first();

            if (! $tipo) {
                $tipo = TipoImovel::first();
            }
            if (! $status) {
                $status = StatusImovel::first();
            }

            Imovel::factory()->create([
                'user_id' => 1,
                'titulo' => $imovel['titulo'],
                'descricao' => $imovel['descricao'],
                'situacao' => $imovel['situacao'],
                'tipo_id' => $tipo->id,
                'status_id' => $status->id,
                'preco' => $imovel['preco'],
                'preco_iptu' => $imovel['preco_iptu'] ?? null,
                'preco_condominio' => $imovel['preco_condominio'] ?? null,
                'area' => $imovel['area'],
                'quartos' => $imovel['quartos'],
                'banheiros' => $imovel['banheiros'],
                'vagas_garagem' => $imovel['vagas_garagem'],
                'endereco' => $imovel['endereco'],
                'bairro' => $imovel['bairro'],
                'cidade' => $imovel['cidade'],
                'estado' => $imovel['estado'],
                'pais' => $imovel['pais'],
                'cep' => $imovel['cep'],
                'caracteristicas' => $imovel['caracteristicas'],
                'fotos' => $imovel['fotos'],
                // 'videos' => $imovel['videos'] ?? [],
                'destaque' => $imovel['destaque'],
                // 'localizacao_maps' => $imovel['localizacao_maps'] ?? null,
                'area_util' => $imovel['area_util'] ?? null,
                'terreno' => $imovel['terreno'] ?? null,
                'area_constr' => $imovel['area_constr'] ?? null,
            ]);
        }
    }
}
